import{useState}from'react';import{View,Text,TextInput,TouchableOpacity,KeyboardAvoidingView,Platform,ScrollView,ActivityIndicator,Alert}from'react-native';import{router}from'expo-router';import{SafeAreaView}from'react-native-safe-area-context';import*as Haptics from'expo-haptics';import{useAuth}from'../../lib/auth-context';import{Colors,Typography,Radius}from'../../constants/design';
export default function Join(){const{joinAsChild}=useAuth();const[code,setCode]=useState('');const[name,setName]=useState('');const[loading,setLoading]=useState(false);
const handleCode=(t)=>{const c=t.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);setCode(c);if(c.length===6)Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success)};
const submit=async()=>{if(code.length!==6||name.trim().length<2){Alert.alert('Check details','Enter the 6-character invite code and your name.');return};setLoading(true);const{error}=await joinAsChild({inviteCode:code,displayName:name.trim()});setLoading(false);if(error){Haptics.notificationAsync(Haptics.NotificationFeedbackType.Error);Alert.alert('Could not join',error)}};
return(<SafeAreaView style={{flex:1,backgroundColor:Colors.bg}}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':'height'} style={{flex:1}}><ScrollView contentContainerStyle={{flexGrow:1,padding:24,gap:16}} keyboardShouldPersistTaps="handled">
<TouchableOpacity onPress={()=>router.back()}><Text style={{fontFamily:Typography.family.medium,fontSize:15,color:Colors.cyan,marginBottom:8}}>← Back</Text></TouchableOpacity>
<View style={{alignItems:'center',gap:12,marginVertical:16}}><Text style={{fontSize:52}}>👾</Text><Text style={{fontFamily:Typography.family.extraBold,fontSize:28,color:Colors.text}}>Join your family</Text><Text style={{fontFamily:Typography.family.regular,fontSize:15,color:Colors.text2,textAlign:'center',lineHeight:22}}>Ask your parent for the 6-character invite code from their PlayPass app.</Text></View>
<View style={{gap:6}}><Text style={{fontFamily:Typography.family.bold,fontSize:11,color:Colors.text3,textTransform:'uppercase',letterSpacing:0.5}}>Invite code</Text>
<TextInput style={{backgroundColor:Colors.card2,borderRadius:Radius.md,borderWidth:code.length===6?2:1.5,borderColor:code.length===6?Colors.green:Colors.border2,paddingHorizontal:16,height:64,fontFamily:Typography.family.extraBold,fontSize:28,color:Colors.text,letterSpacing:8,textAlign:'center'}} placeholder="ABC123" placeholderTextColor={Colors.text3} value={code} onChangeText={handleCode} autoCapitalize="characters" autoCorrect={false} maxLength={6}/>
{code.length===6&&<Text style={{fontFamily:Typography.family.bold,fontSize:13,color:Colors.green}}>✓ Code looks good!</Text>}</View>
<View style={{gap:6}}><Text style={{fontFamily:Typography.family.bold,fontSize:11,color:Colors.text3,textTransform:'uppercase',letterSpacing:0.5}}>Your name</Text>
<TextInput style={{backgroundColor:Colors.card2,borderRadius:Radius.md,borderWidth:1.5,borderColor:Colors.border2,paddingHorizontal:16,height:52,fontFamily:Typography.family.regular,fontSize:15,color:Colors.text}} placeholder="What do people call you?" placeholderTextColor={Colors.text3} value={name} onChangeText={setName} autoCapitalize="words" returnKeyType="done" onSubmitEditing={submit}/></View>
<TouchableOpacity style={{height:52,backgroundColor:Colors.cyan,borderRadius:Radius.lg,alignItems:'center',justifyContent:'center',opacity:loading?0.6:1}} onPress={submit} disabled={loading}>{loading?<ActivityIndicator color={Colors.bg}/>:<Text style={{fontFamily:Typography.family.extraBold,fontSize:17,color:Colors.bg}}>Join family 🎮</Text>}</TouchableOpacity>
<Text style={{fontFamily:Typography.family.regular,fontSize:13,color:Colors.text3,textAlign:'center',lineHeight:20}}>You'll earn Pass Time by completing missions assigned by your parent.</Text>
</ScrollView></KeyboardAvoidingView></SafeAreaView>)}