import{useState}from'react';import{Text,TextInput,TouchableOpacity,KeyboardAvoidingView,Platform,ScrollView,ActivityIndicator,Alert,View}from'react-native';import{router}from'expo-router';import{SafeAreaView}from'react-native-safe-area-context';import{useAuth}from'../../lib/auth-context';import{Colors,Typography,Radius}from'../../constants/design';
export default function Signup(){const{signUp}=useAuth();const[step,setStep]=useState(1);const[familyName,setFamilyName]=useState('');const[displayName,setDisplayName]=useState('');const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[loading,setLoading]=useState(false);
const inp={backgroundColor:Colors.card2,borderRadius:Radius.md,borderWidth:1.5,borderColor:Colors.border2,paddingHorizontal:16,height:52,fontFamily:Typography.family.regular,fontSize:15,color:Colors.text};
const submit=async()=>{if(!email.includes('@')||password.length<8){Alert.alert('Check details','Valid email and password of 8+ characters required.');return};setLoading(true);const{error}=await signUp({email,password,displayName,familyName});setLoading(false);if(error)Alert.alert('Sign up failed',error)};
return(<SafeAreaView style={{flex:1,backgroundColor:Colors.bg}}><KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':'height'} style={{flex:1}}><ScrollView contentContainerStyle={{flexGrow:1,padding:24,gap:16}} keyboardShouldPersistTaps="handled">
<TouchableOpacity onPress={()=>step===2?setStep(1):router.back()}><Text style={{fontFamily:Typography.family.medium,fontSize:15,color:Colors.indigoLight,marginBottom:8}}>← Back</Text></TouchableOpacity>
<View style={{flexDirection:'row',alignItems:'center',gap:8,marginBottom:16}}><View style={{width:10,height:10,borderRadius:5,backgroundColor:Colors.indigo}}/><View style={{flex:1,height:2,backgroundColor:step===2?Colors.indigo:Colors.border}}/><View style={{width:10,height:10,borderRadius:5,backgroundColor:step===2?Colors.indigo:Colors.border2}}/></View>
<Text style={{fontFamily:Typography.family.extraBold,fontSize:28,color:Colors.text}}>{step===1?'Create your family':'Secure your account'}</Text>
<Text style={{fontFamily:Typography.family.regular,fontSize:15,color:Colors.text2,marginBottom:8}}>{step===1?'Your family name and your name as parent.':'Almost done — set your login details.'}</Text>
{step===1?(<><TextInput style={inp} placeholder="Family name (e.g. The Johnsons)" placeholderTextColor={Colors.text3} value={familyName} onChangeText={setFamilyName} autoCapitalize="words"/>
<TextInput style={inp} placeholder="Your name (e.g. Mum or Dad)" placeholderTextColor={Colors.text3} value={displayName} onChangeText={setDisplayName} autoCapitalize="words"/>
<TouchableOpacity style={{height:52,backgroundColor:Colors.indigo,borderRadius:Radius.lg,alignItems:'center',justifyContent:'center'}} onPress={()=>{if(familyName.trim().length>=2&&displayName.trim().length>=2)setStep(2);else Alert.alert('Check details','Both fields need at least 2 characters.')}}><Text style={{fontFamily:Typography.family.extraBold,fontSize:17,color:'#fff'}}>Continue →</Text></TouchableOpacity></>):(<>
<TextInput style={inp} placeholder="Email address" placeholderTextColor={Colors.text3} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address"/>
<TextInput style={inp} placeholder="Password (8+ characters)" placeholderTextColor={Colors.text3} value={password} onChangeText={setPassword} secureTextEntry/>
<TouchableOpacity style={{height:52,backgroundColor:Colors.indigo,borderRadius:Radius.lg,alignItems:'center',justifyContent:'center',opacity:loading?0.6:1}} onPress={submit} disabled={loading}>{loading?<ActivityIndicator color="#fff"/>:<Text style={{fontFamily:Typography.family.extraBold,fontSize:17,color:'#fff'}}>Create family account</Text>}</TouchableOpacity></>)}
<TouchableOpacity onPress={()=>router.replace('/(auth)/login')} style={{alignItems:'center'}}><Text style={{color:Colors.text2,fontFamily:Typography.family.regular,fontSize:13}}>Already have an account? <Text style={{color:Colors.indigoLight,fontFamily:Typography.family.bold}}>Sign in</Text></Text></TouchableOpacity>
</ScrollView></KeyboardAvoidingView></SafeAreaView>)}